### ISSUE TITLE
Proposal Added

### ISSUE THREAD

**Issue by alexkoveos** [alexkoveos/final_project#1]
@amcooper @jasonseminara @WilliamfShaw @zhenpanda 

Hey added a .md with a proposal! Thanks!

**Comment by jasonseminara** [comment]
@alexkoveos, This seems promising, but I'm not 100% sure how the mechanics of this would function. I vaguely remember some game from the late 90's that was similar: it brought you to some far-flung websites and you collected clues for the game. 

How would your game work exactly?

**Comment by jasonseminara** [comment]
@alexkoveos, 

Any ideas to clear up the game mechanics?

**Comment by jasonseminara** [comment]
Please respond and reassign this ticket to me

**Comment by alexkoveos** [comment]
###### Final Project Proposal Take 2

For my final project I have started working on a platforming game using the JavaScript based Phaser engine. The concept will be navigating through increasingly harder jumping challenges. The levels will use phaser’s scrolling ability to follow the player to an end goal which will load a next level. Ultimately there will be a final level with a game over screen taking the player to the end. Along the way checkpoints will be enabled to allow the player to continue progress and not have to start over.
![title_screen_example](https://cloud.githubusercontent.com/assets/14540171/11698309/f28b4a58-9e8b-11e5-9477-57c4ca77cf87.png)
![level_example](https://cloud.githubusercontent.com/assets/14540171/11698318/fadb3556-9e8b-11e5-964a-0f4139eb1b24.png)

**Comment by jasonseminara** [comment]
approved. Don't bite off more than you can chew
